server:
  port: 8801
spring:
  application:
    name: eureka-server # 应用名称，会在Eureka中显示
eureka:
  instance:
    hostname: localhost
  server:
     eviction-interval-timer-in-ms: 1000 # 剔除失效的服务  默认60s检测剔除一次失效服务    参数单位：ms
     enable-self-preservation: false # 关闭自我保护模式（缺省为打开）
  client:
#    registerWithEureka: false # 是否注册自己的信息到EurekaServer，默认是true
#    fetchRegistry: false  #是否拉取其它服务的信息，默认是true
    serviceUrl: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://${eureka.instance.hostname}:8800/eureka/
