
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/,http://localhost:8801/eureka/
  instance:
      lease-expiration-duration-in-seconds: 10 #服务失效时间，默认值90秒    如果超过90秒没有发送心跳，EurekaServer就会认为该服务宕机，会从服务列表中移除
      lease-renewal-interval-in-seconds: 5 #默认情况下每个30秒服务会向注册中心发送一次心跳，证明自己还活着

server:
  port: 8802
spring:
  application:
    name: ribbon-provider
