data:
  env: config-eureka-dev
  version: 1.0.4

#自动刷新配置用      
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8802
spring:
  application:
    name: ribbon-provider
